// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 12.08.2024, 16:09:23
const configMerger = require("G:/OSPanel/home/testapp.local/frontend/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["G:/OSPanel/home/testapp.local/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/OSPanel/home/testapp.local/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/OSPanel/home/testapp.local/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/OSPanel/home/testapp.local/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/OSPanel/home/testapp.local/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/OSPanel/home/testapp.local/frontend/plugins/**/*.{js,ts,mjs}","G:/OSPanel/home/testapp.local/frontend/composables/**/*.{js,ts,mjs}","G:/OSPanel/home/testapp.local/frontend/utils/**/*.{js,ts,mjs}","G:/OSPanel/home/testapp.local/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","G:/OSPanel/home/testapp.local/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","G:/OSPanel/home/testapp.local/frontend/app.config.{js,ts,mjs}"] }));

module.exports = config
